image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
vscode:
  extensions:
    - Unity.unity-debug@2.7.2:hsmEyRRXbt8udUUkD43Mmw==
    - ms-vscode.csharp@1.21.4:lLV3lBwYKRTJ3QAQjtNMaQ==
    - Tobiah.unity-tools@1.1.1:BxAZIio1njang4v291eq1w==
    - YclepticStudios.unity-snippets@0.1.2:QF7EkNatPDYQ71do0+fFFQ==